
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ISBN = 8.878417E+08F,
    User_ID = 8F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Book_Rating with predicted Book_Rating from sample data...\n\n");


Console.WriteLine($"ISBN: {8.878417E+08F}");
Console.WriteLine($"User_ID: {8F}");
Console.WriteLine($"Book_Rating: {5F}");


var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Book_Rating: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

